// Font families available - generated by download-fonts.ps1
window._LOCAL_FONTS = [
  'Blast Bold Hollow',
  'Boingster',
  'Bw Surco',
  'cour',
  'Edirne-Normal_cyrillic',
  'Furore',
  'good vides pro',
  'josefkpaneuropean',
  'Monomakh',
  'Neuzeit Antiqua',
  'Preciosa',
  'Preciosa Valeria',
  'Rodondo RUS',
  'timesnewromanpsmt',
  'Tobi Greek',
  'Transita Modern',
  'VMVTZARCARI'
];