// Font families available - generated by download-fonts.ps1
window._LOCAL_FONTS = [
  'Blast Bold Hollow',
  'Bw Surco',
  'josefkpaneuropean2',
  'Neuzeit Antiqua',
  'Preciosa',
  'Preciosa Valeria',
  'Rodondo RUS',
  'Tobi Greek',
  'Transita Modern',
  'VMVTZARCARI',
];


